# Generated by Django 2.2.16 on 2022-09-19 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20220919_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_post', to='posts.Post'),
        ),
    ]
